# Spring Boot configuration
spring:
  profiles:
    active: development
  # Security configuration
  security:
    user:
      name: user
      password: user
  # Database
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ieeuns?useSSL=false
    username: root
    password: 123456
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: create # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false
    generate-ddl: true
# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug
# Server configuration
server:
  port: 8092 #set your port
  error:
    include-message: always
    include-binding-errors: always
