#Application Configuration
server:
  port: 8092

# To See H2 Console in Browser:
# http://localhost:8091/h2-console
# Enabling H2 Console
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ieeuns_v2
    username: root
    password: 123456
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
